CI/CD initial workflow
aktin/debian-i2b2-pkg pull request #17
Opened 2024-12-18 11:01 UTC by bunbry

Workflow implementing steps for building and deployment. The steps consist of reusable workflows, making this PR dependent on aktin/aktin-github-scripts#2

2025-01-21 13:26 UTC, akomii commented on .github/workflows/ci-dev.yml
> +  #        run:  # TODO
I would remove this for now. The job will only do build and deploy. Continous testing will be added at a later time

2025-01-21 13:26 UTC, akomii commented on .github/workflows/ci-dev.yml
> +      codename: 'testing'
The release type should be included in the codename, so "jammy-testing" is the correct name. But as the name of the job is ci-dev, maybe "jammy-devel" would be more appropriate? Its up to you...

2025-01-21 13:26 UTC, akomii commented on .github/workflows/ci-rc.yml
> +  #        run:  # TODO
Again, I would cut the tests for now and add them later because they are a task in themselves and be fully fleshed out. Otherwise the tests will just take a long time to complete (because of the installation and configuration) and offer no additional value

2025-01-21 13:26 UTC, akomii commented on .github/workflows/ci-rc.yml
> +      codename: 'unstable'
Should be "jammy-unstable"

2025-01-23 14:39 UTC, bunbry commented on .github/workflows/ci-dev.yml
> +      codename: 'testing'
`testing` feels appropriate for builds which are deployed untested and are in the process of being (manually) tested. `dev` or `development` feels more neutral regarding the test status of the builds (either untested or some automated tests were perform before deployment, depending on the context of the development process).
I would suggest using `jammy-dev`.

2025-01-23 15:31 UTC, bunbry commented on .github/workflows/ci-dev.yml
> +      codename: 'testing'
I just looked into the naming conventions for the codenames, and it looks like we have **`unstable`** and **`testing`** mixed up (see this [FAQ](https://www.debian.org/doc/manuals/debian-faq/ftparchives.en.html), Sections 6.1 and 6.4 - 6.6 in particular).
Our **`testing`** distribution should be named **`unstable`** and vice versa.

2025-01-23 15:33 UTC, bunbry commented on .github/workflows/ci-rc.yml
> +      codename: 'unstable'
Same as this https://github.com/aktin/debian-i2b2-pkg/pull/17#discussion_r1927179224

2025-01-29 10:19 UTC, akomii requested changes

2025-01-29 10:19 UTC, akomii commented on .github/workflows/ci-rc.yml
> +      codename: 'jammy-testing'
To make things simple: I would remove `ci-dev.yml` and only keep the deployment of tagged commits directly on testing. An unstable development branch can be added in a later iteration

2025-01-29 10:20 UTC, akomii commented on .github/workflows/ci-dev.yml
> +      codename: 'testing'
Yes, this will be done

2025-02-06 15:19 UTC, akomii approved these changes

2025-02-06 15:22 UTC, merged